### PR TITLE
Convert to associated constants

### PR DESCRIPTION
**Pull request by tamird**
Two problems with this:
- breaking API change
- requires nightly

I suppose this will need to wait until associated constants are stable.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Yeah for now this crate builds on stable, so we'll have to wait for associated constants to be stable to merge this unfortunately.

**Comment by phil-opp** [comment]
@tamird It seems like the `associated_const` feature will remain unstable for the near future. So it might make sense to pre-release this on crates.io as a separate crate (e.g. `bitflags_associated_consts`). This would allow nightly users to take advantage of the nicer API.

**Comment by tamird** [comment]
This needs a rebase to pick up various changes made on master; I'll try to get to it this week.

**Comment by tamird** [comment]
Rebased; probably won't pass until 1.20 is stable.

**Comment by tamird** [comment]
Rebased again. Beyond the use of associated constants, this also uses compiletest, which requires nightly. Do we want to just remove the compile-fail test?

**Comment by alexcrichton** [comment]
The stable/beta builds seem to still be failing due to experimental features?

**Comment by tamird** [comment]
Yes, I believe that's because this PR adds a dependency on compiletest, which requires nightly (see my last comment). Should I just remove the compile-fail tests?

**Comment by tamird** [comment]
Removed compiletest; lmk if you'd like me to squash the commits, but this should be green now.

**Comment by alexcrichton** [comment]
👍 

Thanks @tamird!

**Pull request merged**
