### PR TITLE
Make it able to build in the rust buildchain

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Can you back out the version bump? After that I'll merge

**Comment by GuillaumeGomez** [comment]
I need it to be published in a new version in order to let pulldown-cmark depends on the new one. Or maybe you'd prefer to handle the version change yourself?

**Comment by GuillaumeGomez** [comment]
I removed the version bump.

**Comment by alexcrichton** [comment]
Yes, there's other changes in flight, this'll get lumped in with those.

**Pull request merged**
