### PR TITLE
s/$BitFlags/Self/g

### PR DESCRIPTION
**Pull request by tamird**
@alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Does this affect the generated documentation?

**Comment by tamird** [comment]
Doesn't seem like it does. The string "$BitFlags" doesn't appear in the documentation outside of the macro definition, which is unchanged here.

**Comment by tamird** [comment]
Well, it does appear in `doc/src/bitflags/lib.rs.html` (where it is now replaced with "Self"), but that's expected since that's the source itself.

**Comment by alexcrichton** [comment]
Oh sorry I meant moreso the generated docs for the bitflags struct that this generates. I'd expect the identifier of the struct to be much more readable than `Self` (e.g. more obvious at a glance), so if there's not a technical reason for this I'd err on the side of more self-explanatory docs.

If there's a technical reason to do this, though, please let me know!

**Comment by tamird** [comment]
Well, it does replace the struct name with "Self". However, isn't that true of all implementations that use Self? If documentation is considered clearer with the explicit type name, perhaps that's a transformation that should be applied to all docs?

**Comment by alexcrichton** [comment]
I would personally consider `Self` less readable than the struct name itself. Sure I can always remember to perform the transformation, but it seems better if I don't have to do it in the first place.

Can you elaborate on the motivation for this PR?

**Comment by tamird** [comment]
Sorry, I didn't mean to suggest a mental transformation - I meant that it should be possible to universally apply the transformation at the docs generation stage.

The motivation is just to reduce duplication.

**Comment by alexcrichton** [comment]
Yeah definitely rustdoc *could* do that, but it doesn't currently afaik :(

In that sense would you be ok closing until that's a feature in rustdoc?

**Comment by tamird** [comment]
Sure thing.

**Pull request closed without merging**
