### PR TITLE
Add u128 feature for complete u128 compatibility

### PR DESCRIPTION
**Pull request by astocko**
Added a u128 feature with a feature gated bitflags width type for use in the macro. Enables functionality like debug formatting of flags that exceed 64 bits. #56

### CODE REVIEW

**Comment by alexcrichton** [comment]
This seems to only be used in the formatting pieces, and there could we just use `$T` instead of an explicit size? That way we could defer this decision entirely to downstream crates I think?

**Comment by astocko** [comment]
Implemented as suggested. The change does require absolute paths for custom types and type aliases.

**Comment by alexcrichton** [comment]
Oh right sorry I forgot about that :(, that's actually a pretty crucial reason for this feature.

In that case I guess we'll have to stick with an unstable feature

**Comment by astocko** [comment]
I will revert to my original PR. Any comments or suggestions?

**Comment by alexcrichton** [comment]
Looks like this may still be the requires-absolute-paths version?

**Comment by alexcrichton** [comment]
Thanks!

**Comment by dtolnay** [comment]
#61 reimplements this in a different way that neither requires absolute paths nor a cfg to opt into u128 compatibility.

**Pull request merged**
