### PR TITLE
no_std is stable now

### PR DESCRIPTION
**Pull request by Ericson2314**
Not sure if we still want `__core`

### CODE REVIEW

**Comment by Amanieu** [comment]
We still need `__core` because we don't know whether the crate using `bitflags!` has `core` or `std`, and it could even have overridden these names to mean something else entirely. Therefore the only reliable way of referring to `core` is through `$crate::__core`.

**Comment by Amanieu** [comment]
However note that removing the `no_std` Cargo feature is a breaking change. We could leave it as a no-op or remove it and bump our version number.

**Comment by Ericson2314** [comment]
Hmm I would just bump it. Don't think this crate is ready for 1.0 and less churn until associated types are stable anyways.

Also, is `pub extern crate` a thing? Can we do that with `$crate::core` and drop the underscores?

**Comment by Amanieu** [comment]
I think `pub extern crate` currently gives a warning saying it doesn't work properly and that you should use `pub use` instead.

The reason I added underscores was because `__core` is not part of the API of this crate, it only needs to be publicly exported so that it can be used by the macro.

**Comment by Ericson2314** [comment]
Alright, makes sense. I'll try `pub extern crate core as __core`, and bump the version.

**Comment by Ericson2314** [comment]
https://github.com/rust-lang/rust/issues/26775 Ok `pub extern crate` is currently broken.

**Comment by Ericson2314** [comment]
Nevermind, it does work after all. Used that, and bumped version number, so this should be ready to go.

**Comment by Amanieu** [comment]
Travis doesn't seem to agree (see below)

**Comment by Ericson2314** [comment]
Ah, I only tested on nightly oops. I'll revert that, and fix the Travis error on the other two where it tries to build with the no_std feature.

**Comment by phil-opp** [comment]
I think you can just do a:

```
pub use core as __core;
```

The `extern crate core` is not needed since it's imported automatically when using `#![no_std]`.

**Comment by Ericson2314** [comment]
@phil-opp It's needed for tests when `#![no_std]` is disabled.

**Comment by alexcrichton** [comment]
Looks like CI is failing? Otherwise seems like a good change to me!

**Comment by Ericson2314** [comment]
Ok, fixed problems. Also made it always use `#![no_std]` and conditionally import std for tests, which seems more idiomatic.

**Comment by alexcrichton** [comment]
Can you back out the version bump? That's typically done as a separate commit

**Comment by Ericson2314** [comment]
Separate PR I assume you mean? Unless I messed up it is a separate commit ATM.

**Comment by alexcrichton** [comment]
Yes, separate PR (or I'll just do it when I merge this)

**Comment by Ericson2314** [comment]
Sure. I'll just remove the commit then.

**Comment by Ericson2314** [comment]
Done!

**Pull request merged**
