### PR TITLE
Add compile-fail tests for private associated constants

### PR DESCRIPTION
**Pull request by tamird**
r? @alexcrichton 

This wanted to be in #24, but I didn't know how to do it.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Can this be orchestrated as a separate crate to avoid the `[dependencies]` section?

**Comment by tamird** [comment]
Done.

**Comment by alexcrichton** [comment]
Can you update CI to run these tests as well?

**Comment by tamird** [comment]
@alexcrichton I did - see the new `travis-cargo --only nightly test --all` in `.travis.yml`.

**Comment by tamird** [comment]
See this line in the test output: `test [compile-fail] compile-fail/private_flags.rs ... ok`


https://travis-ci.org/rust-lang-nursery/bitflags/jobs/273616109

**Comment by tamird** [comment]
@alexcrichton anything more required here? Travis mac builds are broken (see https://www.traviscistatus.com/).

**Comment by alexcrichton** [comment]
Ah sorry I missed the `--all`!

**Pull request merged**
